name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4  # Corrigido para a ação de checkout correta

      - name: Simulating delivery
        run: echo "Simulating delivery step..."  # Exemplo de comando simples, substitua conforme necessário

      - name: Archive files into a tar (instead of zip)
        run: |
          echo "Creating the tarball..."
          tar -czf $GITHUB_WORKSPACE/test.tar.gz **/*.java README.md  # Compacta os arquivos em um tar.gz
          echo "Tarball created at $GITHUB_WORKSPACE/test.tar.gz"
        
      - name: Save the artifact manually
        run: |
          echo "Moving tarball to the artifacts directory"
          mkdir -p $GITHUB_WORKSPACE/artifacts
          mv $GITHUB_WORKSPACE/test.tar.gz $GITHUB_WORKSPACE/artifacts/  # Move o arquivo para o diretório correto
          echo "Tarball moved to $GITHUB_WORKSPACE/artifacts/test.tar.gz"

  deploy:
    runs-on: ubuntu-latest
    needs: deliver  # Define que o job deploy depende do job deliver

    steps:
      - name: Download artifact manually
        run: |
          echo "Checking if the artifact exists..."
          ls -lh $GITHUB_WORKSPACE/artifacts/  # Verifica se o arquivo está no diretório
          cp $GITHUB_WORKSPACE/artifacts/test.tar.gz .  # Copia o arquivo para o diretório atual
          echo "Extracting the tarball..."
          tar -xvzf test.tar.gz  # Extrai o tar.gz para o diretório atual

      - name: Display structure of downloaded files
        run: ls -R  # Exibir a estrutura de arquivos do artefato extraído
