name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Simulate delivery
        run: echo "Simulating delivery step..."

      - name: Archive files into a tar (instead of zip)
        run: |
          echo "Creating the tarball..."
          tar -czf $GITHUB_WORKSPACE/test.tar.gz **/*.java README.md
          echo "Tarball created at $GITHUB_WORKSPACE/test.tar.gz"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: test-artifact
          path: $GITHUB_WORKSPACE/test.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: deliver

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Download artifact
        uses: actions/download-artifact@v4  # Atualizado para v4
        with:
          name: test-artifact
