name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4  # Corrigido para a ação de checkout correta

      - name: Simulating delivery
        run: echo "Simulating delivery step..."  # Exemplo de comando simples, substitua conforme necessário

      - name: Archive files into a zip (Optional)
        run: zip -r test.zip **/*.java README.md  # Exemplo de como compactar arquivos especificados

      - name: Upload artifact
        uses: actions/upload-artifact@v2  # Atualizado para v2
        with:
          name: test.zip
          path: test.zip

  deploy:
    runs-on: ubuntu-latest
    needs: deliver  # Define que o job deploy depende do job deliver

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2  # Use v2 para a ação download-artifact também
        with:
          name: test.zip  # Nome do artefato a ser baixado

      - name: Display structure of downloaded files
        run: ls -R  # Exibir a estrutura de arquivos do artefato baixado
