name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Simulate delivery
        run: echo "Simulating delivery step..."

      - name: Archive files into a tar (instead of zip)
        run: |
          echo "Creating the tarball..."
          tar -czf $GITHUB_WORKSPACE/test.tar.gz **/*.java README.md
          echo "Tarball created at $GITHUB_WORKSPACE/test.tar.gz"
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: $GITHUB_WORKSPACE/test.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: deliver  # Este job depende do job "deliver"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: test-artifact  # O nome do artefato que foi carregado no job anterior

      - name: Extract the tarball
        run: |
          echo "Extracting the tarball..."
          tar -xvzf test.tar.gz  # Extrai o tar.gz para o diretório atual

      - name: Display structure of downloaded files
        run: ls -R  # Exibe a estrutura de arquivos do artefato extraído
