# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4  # Corrigido para a ação de checkout correta
      
      - name: Simulating delivery
        run: echo "Simulating delivery step..."  # Exemplo de comando simples, substitua conforme necessário

      - name: Archive files into a zip (Optional)
        run: zip -r test.zip **/*.java README.md  # Exemplo de como compactar arquivos especificados

      - name: Upload artifact
        uses: actions/upload-artifact@v3  # Enviar o arquivo zipado como artefato
        with:
          name: test.zip
          path: test.zip

  deploy:
    runs-on: ubuntu-latest
    needs: deliver  # Define que o job deploy depende do job deliver

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: test.zip  # Nome do artefato a ser baixado

      - name: Display structure of downloaded files
        run: ls -R  # Exibir a estrutura de arquivos do artefato baixado
