name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # A versão v2 da ação de checkout pode ser mais estável

      - name: Simulate delivery
        run: echo "Simulating delivery step..."

      - name: Archive files into a tar (instead of zip)
        run: |
          echo "Creating the tarball..."
          tar -czf $GITHUB_WORKSPACE/test.tar.gz **/*.java README.md
          echo "Tarball created at $GITHUB_WORKSPACE/test.tar.gz"
        
      - name: Upload artifact (using v1 for better stability)
        uses: actions/upload-artifact@v1
        with:
          name: test-artifact
          path: $GITHUB_WORKSPACE/test.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: deliver  # Este job depende do job "deliver"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Usando a versão v2 do checkout

      - name: Download artifact (using v1 for better stability)
        uses: actions/download-artifact@v1
        with:
          name: test-artifact  # O nome do artefato carregado no jo
