# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: continuousdelivery

on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
      - uses: actions/checkout@v4uses

      - name: simulando delivery
      - uses: actions/checkout@v4uses
        with:
          name: test.zip
          path: |
            '**.java'
            README.md

  deploy:
    runs-on : ubuntu-lastest
    needs : deliver
    steps:
        - uses: actions/download-artifact@v5
          with:
            name: test.zip
        - name: Display structure of downloaded files
          run: ls -R
